version: '3.8'

services:
  # MQTT Processor (EMQX Cloud 연결)
  mqtt_processor:
    build:
      context: ./mqtt_processor
      dockerfile: Dockerfile
    container_name: robot_dashboard_mqtt_processor
    ports:
      - "8080:8080"     # WebSocket Bridge
    environment:
      - MQTT_HOST=p021f2cb.ala.asia-southeast1.emqxsl.com
      - MQTT_PORT=8883
      - MQTT_USERNAME=Rokey
      - MQTT_PASSWORD=1234567
      - WS_PORT=8080
      - LOG_LEVEL=info
      - DEBUG_MODE=false
    restart: unless-stopped
    networks:
      - robot_network
    volumes:
      - ./data/logs/mqtt:/app/data/logs/mqtt
      - ./mqtt_processor/config:/app/config:ro

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: robot_dashboard_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
      - MQTT_PROCESSOR_URL=ws://mqtt_processor:8080
    depends_on:
      - mqtt_processor
    restart: unless-stopped
    networks:
      - robot_network
    volumes:
      - ./data/logs/backend:/app/logs
      - ./configs:/app/configs:ro

  # Frontend (for production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: robot_dashboard_frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000
      - REACT_APP_WS_URL=ws://localhost:8080
      - REACT_APP_MQTT_BROKER_URL=ws://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - robot_network

volumes: {}

networks:
  robot_network:
    driver: bridge
